DataCrate/BasicSite/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

app_name = "BasicSite"

urlpatterns = [
    # File Sharing
    path('', Home, name = "Home"),
    path('dashboard',Dashboard,name='Dashboard'),
    path('profile',UserProfile,name='Profile'),
    path('sign-in',SignIn,name='SignIn'),
    path('sign-up',SignUp,name='SignUp'),
    path('logout',Logout,name='Logout'),
]
urlpatterns += staticfiles_urlpatterns()

DataCrate/DataCrate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include('BasicSite.urls',namespace='BasicSite')),
    path('file-transfer/',include('FileTransfer.urls',namespace='FileTransfer')),
    path('editor/',include('Editor.urls',namespace='Editor')),
    path('file-store/',include('FileStore.urls',namespace='FileStore')),
    path('tools-services/',include('ToolsServices.urls',namespace='ToolsServices')),
]

# Serve static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += staticfiles_urlpatterns()

DataCrate/Editor/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

app_name = "Editor"

urlpatterns = [
    # File Sharing
    path('', EditorBase, name = "Editor"),
    path('<str:link>', EditorHome, name = "Editor"),
    path('api/editor-generate-link',EditorGenerateLink, name='EditorGenerateLink'),
]
urlpatterns += staticfiles_urlpatterns()

DataCrate/FileTransfer/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

app_name = "FileShare"

urlpatterns = [
    # File Sharing
    path('', FileShare, name = "FileShare"),
    path('<str:id>',FileDownload,name='FileDownloadByID'),
    path('api/file-upload',FileUpload,name="FileUpload"),
    path('api/file-download/<str:id>',FileDownload,name='FileDownload'),
]
urlpatterns += staticfiles_urlpatterns()

DataCrate/Frontend/templates/Components/Footer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DataCrate | Footer</title>
    <link rel='stylesheet' href="{% static 'css/Components/Footer.css' %}">
</head>
<body>
    <div class="FooterMainwrapper">
        <div class="FooterMainContainer">
            <div class="FooterLeftSection">
                <div class="FooterLogo"> Data Crate </div>
                <div class="FooterDesc"> An Idea to facilitate the file management right from the 
                    file uploads to storage to retrival and much more with an user friendly UI
                    and some special tools to make tasks easier.
                </div>
            </div>
            <div class="FooterRightSection">
                <div class="FooterLinksHolder">
                    <div class="FooterLinkHolderHead"> Quick Links </div>
                    <a href="{% url 'FileShare:FileShare' %}" class="FooterLinkItem"> File Share </a>
                    <a href="{% url 'Editor:Editor' %}" class="FooterLinkItem"> Editor </a>
                    <a href="{% url 'FileStore:Home' %}" class="FooterLinkItem"> File Store </a>
                    <a href="{% url 'ToolsServices:Home' %}" class="FooterLinkItem"> Tools </a>
                </div>
                <div class="FooterLinksHolder">
                    <div class="FooterLinkHolderHead"> Support </div>
                    <a href="{% url 'BasicSite:SignIn' %}" class="FooterLinkItem"> Login </a>
                    <a href="{% url 'BasicSite:SignUp' %}" class="FooterLinkItem"> Sign up </a>
                    <a href="#" class="FooterLinkItem"> FAQ's </a>
                    <a href="#" class="FooterLinkItem"> Help Desk </a>
                </div>
                <div class="FooterLinksHolder">
                    <div class="FooterLinkHolderHead"> Social Handles </div>
                    <a href="#" class="FooterLinkItem"> Email </a>
                    <a href="#" class="FooterLinkItem"> Mobile </a>
                    <a href="#" class="FooterLinkItem"> Instagram </a>
                    <a href="#" class="FooterLinkItem"> Facebook </a>
                </div>
            </div>
        </div>
        <div class="FooterCopyRightContainer"> @Copyrights 2024 belongs to its owner </div>
    </div>
</body>
</html>

DataCrate/Frontend/templates/Components/HomeFeatures.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

<style>

* {
    margin: 0;  
    padding: 0;
    box-sizing: border-box;
}
body {
    --nav-bg-clr : rgb(6 20 11 / 65%);
    --nav-txt-clr :  rgb(78, 75, 75);
    --nav-special-txt-clr : green;
    --nav-highlight-txt-clr : white;
    --nav-anti-highlight-txt-clr : black;
    &.light {
        --nav-bg-clr : rgb(221 227 220 / 17%);
        --nav-txt-clr : rgb(65,68,65);
        --nav-highlight-txt-clr : black;
        --nav-special-txt-clr : green;
        --nav-anti-highlight-txt-clr : white;
    }
}
.FeatureWrapper {
    display: flex;
    align-items: flex-start;
    justify-content: flex-start;
    flex-direction: column;

    width: 100%;
    min-height: 50%;
    height: 50%;
    padding-top: 60px;

    background-color: var(--nav-anti-highlight-txt-clr);
    color: var(--nav-highlight-txt-clr);
}

</style>
</head>
<body>
    <div class="FeatureWrapper">
        ASDF
    </div>
</body>
</html>

DataCrate/Frontend/templates/Components/HomeJumbotron.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

<style>

* {
    margin: 0;  
    padding: 0;
    box-sizing: border-box;
}
body {
    --nav-bg-clr : rgb(6 20 11 / 65%);
    --nav-txt-clr :  rgb(78, 75, 75);
    --nav-special-txt-clr : green;
    --nav-highlight-txt-clr : white;
    --nav-anti-highlight-txt-clr : black;
    &.light {
        --nav-bg-clr : rgb(221 227 220 / 17%);
        --nav-txt-clr : rgb(65,68,65);
        --nav-highlight-txt-clr : black;
        --nav-special-txt-clr : green;
        --nav-anti-highlight-txt-clr : white;
    }
}
.JumboWrapper {
    width: 100%;
    min-height: 100%;
    padding-top: 60px;

    background-color: var(--nav-anti-highlight-txt-clr);
    color: var(--nav-highlight-txt-clr);

    background: url("/static/img/sample.jpeg") 50% 0 no-repeat fixed;
}

</style>
</head>
<body>
    <div class="JumboWrapper">
        <div class="TextOverlayContainer">
            ASDF
        </div>
    </div>
</body>
</html>

DataCrate/Frontend/templates/Components/HorizontalNavBar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Navbar </title>
    <link rel='stylesheet' href="{% static 'css/Components/HorizontalNavBar.css' %}">
</head>
<body>
    <div class="NavMainWrapper" id="mainWrapper">
        <!-- Main Div of the Navbar -->
        <div class="MainContainer">
            <!-- Logo Section -->
            <a href="{% url 'BasicSite:Home' %}" class="LogoSection"> Data Crate </a>

            <div class="HamburgerWrapper">
                <!-- Hamburger Button (Hide in Desktop) -->
                <div class="HamburgerMenu" onclick="toggleHamburger()" id="ham-active">
                    <div class="HamburgerLines HamburgerTop"></div>
                    <div class="HamburgerLines HamburgerMid"></div>
                    <div class="HamburgerLines HamburgerDown"></div>
                </div>

                <!-- Links Section -->
                <div class="NavLinks" id="nav-links">
                    {% if user.is_authenticated %}
                    <div class="NavLink">
                        <a href="{% url 'BasicSite:Dashboard' %}" class="NavLinkHead"> Dashboard </a>
                    </div>
                    {% endif %}
                    <div class="NavLink">
                        <a href="{% url 'FileShare:FileShare' %}" class="NavLinkHead"> File Share </a>
                    </div>
                    <div class="NavLink">
                        <a href="{% url 'Editor:Editor' %}" class="NavLinkHead"> Editor </a>
                    </div>
                    <div class="NavLink">
                        <a href="{% url 'FileStore:Home' %}" class="NavLinkHead"> File Store </a>
                    </div>
                    <div class="NavLink">
                        <a href="{% url 'ToolsServices:Home' %}" class="NavLinkHead"> Tools & Services </a>
                    </div>
                </div>

                <!-- Control Section -->
                <div class="NavMainLinks" id="nav-main-links">
                    {% if user.is_authenticated %}
                    <a href="{% url 'BasicSite:Profile' %}" class="NavMainLink" style="color: green;"> profile </a> 
                    <a href="{% url 'BasicSite:Logout' %}" class="NavMainLink" style="color: red;"> Logout </a>
                    {% else %} 
                    <a href="{% url 'BasicSite:SignIn' %}" class="NavMainLink"> Login </a> 
                    <a href="{% url 'BasicSite:SignUp' %}" class="NavMainLink"> Sign Up </a> 
                    {% endif %}
                    <div onClick="toggleUIMode()" id="switch-mode" class="NavMainLink"
                    style="cursor: pointer;"> D </div>  <!-- Dark/ Light mode -->
                </div>
            </div>

        </div>
    </div>
    <script>
        // Variables
        var hamActive = document.getElementById('ham-active');
        let navLinks = document.getElementById('nav-links');
        let navMainLinks = document.getElementById('nav-main-links');

        function toggleUIMode() {
            var elem = document.body;
            elem.classList.toggle('light');

            var e = document.getElementById('switch-mode');
            if (e.innerText === 'D') {e.innerText = 'W';}
            else {e.innerText = 'D';}
        }
        function toggleHamburger() {
            // toggle the cross.
            hamActive.classList.toggle('activeHamburger');

            // Make the links visible
            if (navLinks.style.display === 'flex') {
                // Order is must as initially navLinks.style.display = ''.
                // This is due to the fact that no inline css is defined.
                navLinks.style.display = 'none';
                navMainLinks.style.display = 'none';
            } else {
                navLinks.style.display = 'flex';
                navMainLinks.style.display = 'flex';
            }
        }
    </script>
</body>
</html>