DataCrate/BasicSite/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

app_name = "BasicSite"

urlpatterns = [
    # File Sharing
    path('', Home, name = "Home"),
    path('dashboard',Dashboard,name='Dashboard'),
    path('profile',UserProfile,name='Profile'),
    path('sign-in',SignIn,name='SignIn'),
    path('sign-up',SignUp,name='SignUp'),
    path('logout',Logout,name='Logout'),
]
urlpatterns += staticfiles_urlpatterns()

DataCrate/DataCrate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include('BasicSite.urls',namespace='BasicSite')),
    path('file-transfer/',include('FileTransfer.urls',namespace='FileTransfer')),
    path('editor/',include('Editor.urls',namespace='Editor')),
    path('file-store/',include('FileStore.urls',namespace='FileStore')),
    path('tools-services/',include('ToolsServices.urls',namespace='ToolsServices')),
]

# Serve static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += staticfiles_urlpatterns()

DataCrate/Editor/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

app_name = "Editor"

urlpatterns = [
    # File Sharing
    path('', EditorBase, name = "Editor"),
    path('<str:link>', EditorHome, name = "Editor"),
    path('api/editor-generate-link',EditorGenerateLink, name='EditorGenerateLink'),
]
urlpatterns += staticfiles_urlpatterns()

DataCrate/ToolsServices/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

app_name = "ToolsServices"

urlpatterns = [
    # File Sharing
    path('', Home, name = "Home"),
    path('special-links',SpecialLinksTool,name="SpecialLinks"),
    path('special-links/<str:linkId>',SpecialLinkPage,name="SpecialLinkPage"),
    
]
urlpatterns += staticfiles_urlpatterns()

DataCrate/ToolsServices/models.py
from django.db import models

# Create your models here.

DataCrate/ToolsServices/views.py
from django.shortcuts import render

# Create your views here.
def Home(request):
    return render(request,"ToolsServices/ToolsServicesHome.html")

def SpecialLinksTool(request):
    return render(request,"ToolsServices/SpecialLinks.html")

def SpecialLinkPage(request, linkId):
    # Get the data corresponding to the link from db.

    data = {
        'linkName' : 'File 0',
        'linkId' : linkId,
    }

    return render(request,'ToolsServices/SpecialLinkPages/SpecialLinkPage.html',context = data)

DataCrate/Frontend/templates/ToolsServices/SpecialLinks.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DataCrate | Special Links</title>
    <link rel="stylesheet" href="{% static 'css/ToolsServices/SpecialLinks.css' %}">
    <link rel="stylesheet" href="{% static 'css/Variables/Variables.css' %}">
</head>
<body>
    {% include 'Components/HorizontalNavBar.html' %}
    <div class="specialLinksWrapper">
        <div class="SpecialLinksContainer">
            <div class="specialLinksHead"> Special Links </div>
            <div class="SpecialLinksTable">
                <div class="SpecialLinksItem">
                    <div class="SpecialLinkItemName"> Link Name </div>
                    <div class="SpecialLinkItemDate"> Last Modified </div>
                </div>
                <div class="SpecialLinksItem">
                    <a href = "{% url 'ToolsServices:SpecialLinkPage' '0as' %}" target="_blank" class="SpecialLinkItemName"> File 0 </a>
                    <div class="SpecialLinkItemDate"> 22/01/2023 - 14:59 </div>
                </div>
                <div class="SpecialLinksItem">
                    <a href = "{% url 'ToolsServices:SpecialLinkPage' 'ase2' %}" target="_blank" class="SpecialLinkItemName"> File 0 </a>
                    <div class="SpecialLinkItemDate"> 22/01/2023 - 14:59 </div>
                </div>
                <div class="SpecialLinksItem">
                    <a href = "{% url 'BasicSite:Dashboard' %}" target="_blank" class="SpecialLinkItemName"> File 0 </a>
                    <div class="SpecialLinkItemDate"> 22/01/2023 - 14:59 </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

DataCrate/Frontend/templates/ToolsServices/ToolsServicesHome.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DataCrate | Tools and Servies </title>
    <link rel="stylesheet" href="{% static 'css/ToolsServices/ToolsServicesHome.css' %}">
    <link rel="stylesheet" href="{% static 'css/Variables/Variables.css' %}">
</head>
<body>
    {% include 'Components/HorizontalNavBar.html' %}
    <div class="ToolsMainWrapper">
        <div class="ToolsMainContainer">
            <div class="ToolsHead">Get your work faster with our tools</div>
            <div class="ToolsHolder">
                <a href="#" class="ToolBox"> Generative AI </a>
                <a href="#" class="ToolBox"> OCR (Image to text) </a>
                <a href="#" class="ToolBox"> File Converter </a>
                <a href="{% url 'ToolsServices:SpecialLinks' %}" class="ToolBox"> Special Links </a>
                <a href="#" class="ToolBox"> Others </a>
            </div>
        </div>
    </div>
</body>
</html>