DataCrate/DataCrate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include('BasicSite.urls',namespace='BasicSite')),
    path('file-transfer/',include('FileTransfer.urls',namespace='FileTransfer')),
    path('editor/',include('Editor.urls',namespace='Editor')),
    path('file-store/',include('FileStore.urls',namespace='FileStore')),
    path('tools-services/',include('ToolsServices.urls',namespace='ToolsServices')),
]

# Serve static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += staticfiles_urlpatterns()

DataCrate/Editor/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

app_name = "Editor"

urlpatterns = [
    # File Sharing
    path('', EditorBase, name = "Editor"),
    path('<str:link>', EditorHome, name = "Editor"),
    path('api/editor-generate-link',EditorGenerateLink, name='EditorGenerateLink'),
]
urlpatterns += staticfiles_urlpatterns()

DataCrate/Editor/models.py
from django.db import models

# Create your models here.

DataCrate/Editor/views.py
import json
from django.shortcuts import render
from django.http import JsonResponse
# Create your views here.
def EditorBase(request):
    data = {
        "name" : "", "content" : "", "data" : "10-01-2023",
    }
    return render(request,"Editor/Editor.html", context = data)

def EditorHome(request, link):
    if link is not None:
        # Get the editor content.
        data = {
            "name" : "Some Name",
            "content" : "Hello World",
            "date" : "10-01-2023",
        }
    else:
        data = {
            "name" : "", "content" : "", "data" : "10-01-2023",
        }
    return render(request,"Editor/Editor.html", context = data)

def EditorGenerateLink(request):
    if request.method == 'POST':
        # Copy this to database.
        print(json.load(request))

        return JsonResponse({'code':'123A'})

DataCrate/Frontend/templates/Editor/Editor.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf_token" content="{{ csrf_token }}">
    <title>DataCrate | Editor</title>
    <link rel="stylesheet" href="{% static 'css/Editor/Editor.css' %}">
    <link rel="stylesheet" href="{% static 'css/Variables/Variables.css' %}">
</head>
<body>
    {% include 'Components/HorizontalNavBar.html' %}
    <div class="EditorMainWrapper">
        <div class="EditorMainContainer">
            <!-- Tool Bar -->
            <div class="EditorToolBar">
                <div class="EditorFileNameContainer">
                    {% if name != "" %}
                    <input type="text" class="EditorFileName" id="file-name-input" placeholder="file name" value={{name}}>
                    {% else %}
                    <input type="text" class="EditorFileName" id="file-name-input" placeholder="file name">
                    {% endif %}
                </div>
                <div class="EditorToolBarOptions">
                    <div class="EditorToolBarOption"> 
                        <div class="EditorToolBarHead"> New </div>
                    </div>
                    <div class="EditorToolBarOption"> 
                        <div class="EditorToolBarHead"> Existing </div>
                    </div>
                    <div class="EditorToolBarOption"> 
                        <div class="EditorToolBarHead"> Clear </div>
                    </div>
                    <div class="EditorToolBarOption"> 
                        <div class="EditorToolBarHead"> Others </div>
                    </div>
                    {% if user.is_authenticated %}
                    <div class="EditorToolBarOption"> 
                        <div class="EditorToolBarHead"> Save </div>
                    </div>
                    {% endif %}
                    <div class="EditorToolBarOption"> 
                        <div class="EditorGenerateLinkBtn" onclick="showLink()"> Generate Link </div>
                    </div>
                </div>
            </div>
            <!-- Editor -->
            <textarea name="editor-main" id="editor-main" class="MainEditorBox"
            placeholder="Write your content here">{{content}}</textarea>

            <!-- Link Generated Slides -->
            <div class="LinkGenerationContainer" id="link-slide">
                <div class="LinkCloseBtn" onclick="closeLink()"> Close </div>
                <a href="#" target="_blank" class="LinkGenerated" id="link-disp"> Some Link </a>
                <div class="LinkBtns">
                    <div class="LinkBtnItem" id="copy-link" onclick="copyFileLink()"> Copy </div>
                    <div class="LinkBtnItem"> Share </div>
                    <div class="LinkBtnItem"> Email </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        let linkDisp = document.getElementById('link-disp');
        let copyLink = document.getElementById('copy-link');
        let editor = document.getElementById('editor-main');
        let linkSlide = document.getElementById('link-slide');
        let filename = document.getElementById('file-name-input');

        function copyFileLink() {
            // paste the link on clipboard
            navigator.clipboard.writeText(linkDisp.innerText);

            // Change the button to copied
            copyLink.innerText = 'Copied';
        }
        function closeLink() {
            linkSlide.style.display = 'none';
            
            // Change the button to copy
            copyLink.innerText = 'Copy';
        }
        async function generateLink() {
            // Send the files to backend via javascript post request.
            let csrf = getCookie('csrftoken');
            // Send a request to the  backend for the code
            var req = await fetch('{% url "Editor:EditorGenerateLink" %}', {
                method: "POST",
                credentials: 'include',
                headers:{
                    'Content-Type': 'application/json',
                    'Accept' : 'application/json',
                    'X-CSRFToken': getCookie('csrftoken'),
                },
                body:JSON.stringify({'content':editor.value,'filename':filename.value}),
            });
            // Get the result you needed.
            var res = await req.json();
            return res.code;
        }
        async function showLink() {
            // Get the code
            const code = await generateLink();
            // Show the display
            linkSlide.style.display = 'flex';
            
            // Update the anchor tag.
            linkDisp.href = `http://127.0.0.1:8000/editor/${code}`;
            linkDisp.innerText = `http://127.0.0.1:8000/editor/${code}`;
        }
        function getCookie(name) {
            const value = `; ${document.cookie}`;
            const parts = value.split(`; ${name}=`);
            if (parts.length === 2) return parts.pop().split(';').shift();
        }
    </script>
</body>
</html>